import type { Metadata } from "next";
import { Encode_Sans_Expanded } from "next/font/google";
import '../../node_modules/@fortawesome/fontawesome-free/css/all.min.css'
import "./globals.css";
import Navbar from "./_component/Navbar";
import Footer from "./_component/Footer";
import NextAuthProvider from "@/Providers/Components/nextauth.providers";
import Providers from "@/Providers/Components/ReactQueryProvider.Provider";
import { ToastContainer } from "react-toastify";

const Encode = Encode_Sans_Expanded({
  subsets: ["latin"],
  weight: ['300', '400']
});


export const metadata: Metadata = {
  title: "Fresh Cart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Encode.className} antialiased`}
      >


        <Providers>
          <ToastContainer></ToastContainer>
          <div className="min-h-screen flex flex-col justify-between">
            <NextAuthProvider>
              <Navbar />

              <div className="container">
                {children}
              </div>
              <Footer />
            </NextAuthProvider>
          </div>

        </Providers>


      </body>
    </html>
  );
}
